const TestPodcastDetails = {
  "id": "23a3612a49cd49549ae6931c6ccdd3b5",
  "title": "The Darkest Timeline with Ken Jeong & Joel McHale",
  "publisher": "Ken Jeong & Joel McHale",
  "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
  "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
  "listennotes_url": "https://www.listennotes.com/c/23a3612a49cd49549ae6931c6ccdd3b5/",
  "total_episodes": 25,
  "explicit_content": false,
  "description": "Quarantined and socially distant within Hollywood; join Ken Jeong & Joel McHale as they FaceTime each other during these strange times to answer all your questions about Community, Coronavirus and all things in between.",
  "itunes_id": 1504921890,
  "rss": "Please upgrade to the PRO plan to see this field",
  "latest_pub_date_ms": 1595916000000,
  "earliest_pub_date_ms": 1585310400023,
  "language": "English",
  "country": "United States",
  "website": "http://darkesttimelinepodcast.libsyn.com/website?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website",
  "extra": {
      "twitter_handle": "",
      "facebook_handle": "",
      "instagram_handle": "",
      "wechat_handle": "",
      "patreon_handle": "",
      "youtube_url": "",
      "linkedin_url": "",
      "spotify_url": "",
      "google_url": "",
      "url1": "",
      "url2": "",
      "url3": ""
  },
  "is_claimed": false,
  "email": "Please upgrade to the PRO plan to see this field",
  "type": "episodic",
  "looking_for": {
      "sponsors": false,
      "guests": false,
      "cohosts": false,
      "cross_promotion": false
  },
  "genre_ids": [
      68,
      67,
      190,
      133,
      109,
      88
  ],
  "episodes": [
      {
          "id": "52bb1219b81045489ede376a9d444ed6",
          "title": "Episode 25 - ALISON BRIE LIVE!",
          "description": "<p class=\"gmail-p1\">Ken & Joel & special guest Alison Brie answer YOUR questions on this virtual live Q&A show! Enjoy!</p> <p class=\"gmail-p1\"> </p> <p class=\"gmail-p1\">Special thanks to OMG VIP and Looped for arranging this special episode.</p>",
          "pub_date_ms": 1595916000000,
          "audio": "https://www.listennotes.com/e/p/52bb1219b81045489ede376a9d444ed6/",
          "audio_length_sec": 5787,
          "listennotes_url": "https://www.listennotes.com/e/52bb1219b81045489ede376a9d444ed6/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/52bb1219b81045489ede376a9d444ed6/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-25-alison-brie-live?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "243b51dd654e42cf9de33b9bfab858b0",
          "title": "Episode 24 - Same-Sex Celebrity Crush - NATHAN FILLION",
          "description": "<p class=\"p1\">Joel remembers the time Ken passed on The Soup before they ever met each other and they unwrap the reason why. Special Guest Nathan Fillion pops in and they all discuss COVID and how he's handling the pandemic. They all discuss  his iconic career: Firefly, Slither, Saving Private Ryan, Castle, The Rookie (renewed for a third season), and even One Life to Live. Oh, and they discuss how Ken came up with his Nathan Fillion shout out on Community's Hot Lava episode and Nathan's subsequent cameos as Janitor Bob Waite in seasons 5 and 6.  Don't miss this one, it's one of our best.</p>",
          "pub_date_ms": 1594620000000,
          "audio": "https://www.listennotes.com/e/p/243b51dd654e42cf9de33b9bfab858b0/",
          "audio_length_sec": 7045,
          "listennotes_url": "https://www.listennotes.com/e/243b51dd654e42cf9de33b9bfab858b0/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/243b51dd654e42cf9de33b9bfab858b0/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-24-same-sex-celebrity-crush-nathan-fillion?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "c54f72223f3f4d58a01bb23ae44821b9",
          "title": "Episode 21 - WHOOPI GOLDBERG",
          "description": "<p>Ken & Joel talk to Whoopi Goldberg about her iconic career, from her career-making award-winning Broadway play to The Color Purple to Star Trek The Next Generation to The View. All this and more, despite Ken getting the interview time wrong.  Also, another Darkest Timeline LIVE this Friday July 3 at 8pm EST/ 5pm PST! Joel & Ken answer YOUR questions! Go to <a title= \"https://www.omgvip.com/kenandjoel/\" href= \"https://www.omgvip.com/kenandjoel/\">https://www.omgvip.com/kenandjoel/</a> for tickets and information.</p>",
          "pub_date_ms": 1594240454001,
          "audio": "https://www.listennotes.com/e/p/c54f72223f3f4d58a01bb23ae44821b9/",
          "audio_length_sec": 4969,
          "listennotes_url": "https://www.listennotes.com/e/c54f72223f3f4d58a01bb23ae44821b9/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/c54f72223f3f4d58a01bb23ae44821b9/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-21-whoopi-goldberg?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "52593c1d6cca47ac82f66cceff186a1f",
          "title": "Episode 22 - Jesus Wept - JIM RASH",
          "description": "<p class=\"p1\">Ken & Joel & special guest Jim Rash answer YOUR questions on this virtual live Q&A show! Enjoy!</p> <p class=\"p1\">Special thanks to OMG VIP and Looped for arranging this special episode.</p>",
          "pub_date_ms": 1594240288002,
          "audio": "https://www.listennotes.com/e/p/52593c1d6cca47ac82f66cceff186a1f/",
          "audio_length_sec": 5981,
          "listennotes_url": "https://www.listennotes.com/e/52593c1d6cca47ac82f66cceff186a1f/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/52593c1d6cca47ac82f66cceff186a1f/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-22-jesus-wept-jim-rash?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "f13cfa2a106a4da2ba220fcd80ded70c",
          "title": "Episode 23 - Most Dominant Guest Ever - SHAQ",
          "description": "<p class=\"p1\">COVID Correspondent Brent Terhune crashes the podcast and they all discuss masks, Mount Rushmore and how they spent their Fourth of July weekend.</p> <p class=\"p1\">Then NBA Hall of Famer SHAQ appears and they discuss EVERYTHING: Kobe, Jordan, Barkley, his rap battle & pilot with Ken, and his show idea with Joel. Most Dominant Interview Ever.</p>",
          "pub_date_ms": 1594188000003,
          "audio": "https://www.listennotes.com/e/p/f13cfa2a106a4da2ba220fcd80ded70c/",
          "audio_length_sec": 6859,
          "listennotes_url": "https://www.listennotes.com/e/f13cfa2a106a4da2ba220fcd80ded70c/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/f13cfa2a106a4da2ba220fcd80ded70c/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-23-most-dominant-guest-ever-shaq?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "b51953cc4d38402980cef6d21bb8184f",
          "title": "Episode 20 - Wear A Mask - BONUS EPISODE",
          "description": "<p>On this bonus episode, Joel & Ken discuss the latest COVID-19 updates. Also, they introduce their COVID Correspondent from Indianapolis Brent Terhune, who we find out is not familiar with the podcast.  Also, another Darkest Timeline LIVE this Friday July 3 at 8pm EST/ 5pm PST! Joel & Ken answer YOUR questions! Go to <a title= \"https://www.omgvip.com/kenandjoel/\" href= \"https://www.omgvip.com/kenandjoel/\">https://www.omgvip.com/kenandjoel/</a> for tickets and information.</p>",
          "pub_date_ms": 1593641072004,
          "audio": "https://www.listennotes.com/e/p/b51953cc4d38402980cef6d21bb8184f/",
          "audio_length_sec": 1643,
          "listennotes_url": "https://www.listennotes.com/e/b51953cc4d38402980cef6d21bb8184f/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest/episode-20-wear-a-mask-bonus-qAX0MOVTZHN-9FtmeAyJvcp.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest/episode-20-wear-a-mask-bonus-qAX0MOVTZHN-9FtmeAyJvcp.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/b51953cc4d38402980cef6d21bb8184f/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-20-wear-a-mask?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "c89cf313b1344a07a476acc69a094ee9",
          "title": "Episode 19 - Virtual Reality",
          "description": "<p class=\"p1\">Joel & Ken with their best guests ever: the fans! Community questions are answered on their first virtual live Q&A show. Special thanks to OMG VIP and Looped for arranging this special episode.</p>",
          "pub_date_ms": 1593250796005,
          "audio": "https://www.listennotes.com/e/p/c89cf313b1344a07a476acc69a094ee9/",
          "audio_length_sec": 5149,
          "listennotes_url": "https://www.listennotes.com/e/c89cf313b1344a07a476acc69a094ee9/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/c89cf313b1344a07a476acc69a094ee9/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-19-virtual-reality?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "2b3973cffde84778b80fee1d07f1a9a8",
          "title": "Episode 18 - Scrunch - SETH GREEN",
          "description": "<p class=\"p1\">Ken & Joel talk about their Father’s Day weekend. Then Seth Green pops in, and they discuss his iconic career from Buffy to Mr. Belvedere to Austin Powers to Robot Chicken to writing, directing & starring in Changeland. Oh, and they discuss how he got the call to appear on the series finale of Community and why Joel gives him coffee grounds in bulk.</p> <p class=\"p1\">The Darkest Timeline LIVE this Friday June 26th at 8pm EST/ 5pm PST! Joel & Ken promise to answer YOUR questions! Go to <a href= \"https://www.omgvip.com/kenandjoel/\">https://www.omgvip.com/kenandjoel/</a> for tickets and information.</p>",
          "pub_date_ms": 1592930671006,
          "audio": "https://www.listennotes.com/e/p/2b3973cffde84778b80fee1d07f1a9a8/",
          "audio_length_sec": 6866,
          "listennotes_url": "https://www.listennotes.com/e/2b3973cffde84778b80fee1d07f1a9a8/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/2b3973cffde84778b80fee1d07f1a9a8/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-18-scrunch-seth-green?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "eb6fb86b824e44b3b132ea12aa4818f0",
          "title": "Episode 17 - The Humble Outsider Who Came In And Nailed It - PAGET BREWSTER",
          "description": "<p class=\"p1\">Ken & Joel discuss a major breakthrough in COVID-19 treatment. Then Paget Brewster joins in and they all discuss her Emmy nomination, Criminal Minds, and the ABC pilot she did with Ken. And of course, they do a deep dive into her season 6 experience on Community.</p>",
          "pub_date_ms": 1592517485007,
          "audio": "https://www.listennotes.com/e/p/eb6fb86b824e44b3b132ea12aa4818f0/",
          "audio_length_sec": 6325,
          "listennotes_url": "https://www.listennotes.com/e/eb6fb86b824e44b3b132ea12aa4818f0/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/eb6fb86b824e44b3b132ea12aa4818f0/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-17-the-humble-outsider-who-came-in-and-nailed-it-paget-brewster?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      },
      {
          "id": "450a74c4f801452aac924299d9ec4825",
          "title": "Episode 16 - Hard Drive & Wing Man - KEITH DAVID",
          "description": "<p class=\"p1\">Ken & Joel discuss why they’ve been on hiatus for two weeks and why it's so hard to return. Then Keith David joins them and they all discuss his legendary career, from his very first movie to his current show Greenleaf (now entering its fifth season) and everything in between. And of course, his time on Community.</p>",
          "pub_date_ms": 1592245544008,
          "audio": "https://www.listennotes.com/e/p/450a74c4f801452aac924299d9ec4825/",
          "audio_length_sec": 6219,
          "listennotes_url": "https://www.listennotes.com/e/450a74c4f801452aac924299d9ec4825/",
          "image": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "thumbnail": "https://cdn-images-1.listennotes.com/podcasts/the-darkest-timeline-with-ken-jeong-joel-1aeSO9y7MNk-VALadJBvq98.300x300.jpg",
          "maybe_audio_invalid": false,
          "listennotes_edit_url": "https://www.listennotes.com/e/450a74c4f801452aac924299d9ec4825/#edit",
          "explicit_content": false,
          "link": "https://darkesttimelinepodcast.libsyn.com/episode-16-hard-drive-wing-man-keith-david?utm_source=listennotes.com&utm_campaign=Listen+Notes&utm_medium=website"
      }
  ],
  "next_episode_pub_date": 1592245544008
}

export default TestPodcastDetails